const arVerbs = {
    pasar: "to pass",
    quedar: "to stay",
    hablar: "to speak",
    llevar: "to carry",
    dejar: "to leave",
    llamar: "to call",
    tomar: "to take",
    tratar: "to treat",
    mirar: "to watch",
    esperar: "to wait for",
    entrar: "to enter",
    trabajar: "to work",
    terminar: "to finish",
    necesitar: "to need",
    resultar: "to turn out (to be)",
    cambiar: "to change",
    presentar: "to introduce",
    crear: "to create",
    considerar: "to consider",
    acabar: "to finish",
    ganar: "to win",
    formar: "to form",
    aceptar: "to accept",
    lograr: "to get",
    preguntar: "to ask",
    estudiar: "to study",
    ayudar: "to help",
    gustar: "to please",
    escuchar: "to listen",
    levantar: "to raise",
    intentar: "to try",
    usar: "to use",
    olvidar: "to forget",
    ocupar: "to occupy",
    fijar: "to fix",
    comprar: "to buy",
    evitar: "to avoid",
    interesar: "to interest",
    echar: "to throw",
    importar: "to import",
    observar: "to observe",
    imaginar: "to imagine",
    desarrollar: "to develop",
    señalar: "to point out",
    preparar: "to prepare",
    faltar: "to lack",
    acompañar: "to accompany",
    desear: "to desire",
    enseñar: "to teach",
    representar: "to represent",
    mandar: "to order (give an order)",
    asegurar: "to assure",
    matar: "to kill",
    guardar: "to guard",
    iniciar: "to initiate",
    bajar: "to lower",
    notar: "to note",
    cortar: "to cut",
    aprovechar: "to take advantage of",
    apoyar: "to support",
    aumentar: "to increase",
    abandonar: "to abandon",
    quitar: "to remove",
    conservar: "to preserve",
    funcionar: "to function",
    anunciar: "to announce",
    comentar: "to comment on",
    participar: "to participate",
    escapar: "to escape",
    tirar: "to throw",
    contestar: "to answer",
    preocupar: "to worry",
    prestar: "to lend",
    pesar: "to weigh",
    viajar: "to travel"
};

const erVerbs = {
    deber: "to owe",
    comprender: "to understand",
    correr: "to run",
    comer: "to eat",
    suceder: "to happen",
    aprender: "to learn",
    responder: "to respond",
    vender: "to sell",
    meter: "to put (in)",
    pretender: "to attempt",
    corresponder: "to correspond with",
    depender: "to depend"
};

const irVerbs = {
    vivir: "to live",
    existir: "to exist",
    ocurrir: "to occur",
    recibir: "to receive",
    permitir: "to permit",
    partir: "to divide",
    cumplir: "to fulfil",
    decidir: "to decide",
    subir: "to go up",
    sufrir: "to suffer",
    compartir: "to share",
    consistir: "to consist",
    insistir: "to insist"
};

const reflexiveArVerbs = {
    lavar: "To wash"
};

const reflexiveErVerbs = {
    atrever: "To dare"
};

const reflexiveIrVerbs = {
    aburrir: "To get bored"
};
